image: node:12.18

variables:
  REPO: gitlab.com
  GROUP: oraksil
  PROJECT: esekki

cache:
  paths:
    - node_modules

before_script:
  - npm i

unit_tests:
  stage: test
  script:
    - npm run typecheck
